# Allows sync'ing of fork with upstream via Github Actions
name: Auto-sync fork

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 2 AM UTC
  workflow_dispatch:     # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/eyaltoledano/claude-task-master.git
          git fetch upstream
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main
          git push origin main